-- Snowflake raw-layer objects for the Bosch manufacturing defect pipeline.
-- Run this before staging or loading sample CSV files.

CREATE DATABASE IF NOT EXISTS MANUFACTURING_DEFECTS;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEFECTS.RAW;

CREATE OR REPLACE FILE FORMAT MANUFACTURING_DEFECTS.RAW.BOSCH_CSV_FORMAT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = FALSE
  NULL_IF = ('')
  TRIM_SPACE = FALSE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE MANUFACTURING_DEFECTS.RAW.BOSCH_SAMPLE_STAGE
  FILE_FORMAT = MANUFACTURING_DEFECTS.RAW.BOSCH_CSV_FORMAT;

CREATE TABLE IF NOT EXISTS MANUFACTURING_DEFECTS.RAW.LOAD_AUDIT (
  DATASET_NAME STRING NOT NULL,
  SOURCE_FILE STRING NOT NULL,
  ROW_COUNT NUMBER NOT NULL,
  LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
