-- Load staged sample CSVs into the raw Snowflake tables.
-- Run 002_create_raw_tables.sql first.

TRUNCATE TABLE IF EXISTS MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC;
TRUNCATE TABLE IF EXISTS MANUFACTURING_DEFECTS.RAW.TRAIN_DATE;
TRUNCATE TABLE IF EXISTS MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL;

COPY INTO MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC
FROM @MANUFACTURING_DEFECTS.RAW.BOSCH_SAMPLE_STAGE
FILES = ('train_numeric_sample.csv.gz')
FILE_FORMAT = (FORMAT_NAME = MANUFACTURING_DEFECTS.RAW.BOSCH_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO MANUFACTURING_DEFECTS.RAW.TRAIN_DATE
FROM @MANUFACTURING_DEFECTS.RAW.BOSCH_SAMPLE_STAGE
FILES = ('train_date_sample.csv.gz')
FILE_FORMAT = (FORMAT_NAME = MANUFACTURING_DEFECTS.RAW.BOSCH_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

COPY INTO MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL
FROM @MANUFACTURING_DEFECTS.RAW.BOSCH_SAMPLE_STAGE
FILES = ('train_categorical_sample.csv.gz')
FILE_FORMAT = (FORMAT_NAME = MANUFACTURING_DEFECTS.RAW.BOSCH_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

INSERT INTO MANUFACTURING_DEFECTS.RAW.LOAD_AUDIT
  (DATASET_NAME, SOURCE_FILE, ROW_COUNT)
SELECT 'numeric', 'train_numeric_sample.csv', COUNT(*)
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC
UNION ALL
SELECT 'date', 'train_date_sample.csv', COUNT(*)
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_DATE
UNION ALL
SELECT 'categorical', 'train_categorical_sample.csv', COUNT(*)
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL;
