-- Basic validation checks after loading sample files into Snowflake.

SELECT
  'numeric' AS dataset_name,
  COUNT(*) AS row_count,
  COUNT(DISTINCT ID) AS distinct_ids,
  COUNT_IF(ID IS NULL) AS null_ids
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC
UNION ALL
SELECT
  'date' AS dataset_name,
  COUNT(*) AS row_count,
  COUNT(DISTINCT ID) AS distinct_ids,
  COUNT_IF(ID IS NULL) AS null_ids
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_DATE
UNION ALL
SELECT
  'categorical' AS dataset_name,
  COUNT(*) AS row_count,
  COUNT(DISTINCT ID) AS distinct_ids,
  COUNT_IF(ID IS NULL) AS null_ids
FROM MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL;

SELECT
  (SELECT COUNT(*) FROM MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC) AS numeric_rows,
  (SELECT COUNT(*) FROM MANUFACTURING_DEFECTS.RAW.TRAIN_DATE) AS date_rows,
  (SELECT COUNT(*) FROM MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL) AS categorical_rows,
  (SELECT COUNT(*)
   FROM MANUFACTURING_DEFECTS.RAW.TRAIN_NUMERIC n
   INNER JOIN MANUFACTURING_DEFECTS.RAW.TRAIN_DATE d USING (ID)
   INNER JOIN MANUFACTURING_DEFECTS.RAW.TRAIN_CATEGORICAL c USING (ID)) AS aligned_ids;
